import {
  Menu,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Check,
  AlertCircle,
  AlertTriangle,
  Info,
  Trash2,
  Search,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  Loader2,
  Moon,
  Sun,
  Laptop,
  User,
  Plus,
  Minus,
  ExternalLink,
  Heart,
  ShoppingCart,
  Globe,
  CreditCard,
  DollarSign,
  Truck,
  ShieldCheck,
  Leaf,
  Star,
  Eye,
  Phone,
  PhoneCall,
  MessageCircle,
  MessageSquare,
} from 'lucide-react';

export const ICONS = {
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  trash: Trash2,
  search: Search,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  spinner: Loader2,
  moon: Moon,
  sun: Sun,
  laptop: Laptop,
  avatar: User,
  user: User,
  plus: Plus,
  minus: Minus,
  externalLink: ExternalLink,
  heart: Heart,
  cart: ShoppingCart,
  facebook: Globe,
  instagram: Globe,
  twitter: Globe,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  truck: Truck,
  shieldCheck: ShieldCheck,
  leaf: Leaf,
  star: Star,
  eye: Eye,
  phone: Phone,
  phoneCall: PhoneCall,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
} as const;

export type IconName = keyof typeof ICONS;

